# Generated by Django 5.2.13 on 2026-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('amenidades', models.JSONField(blank=True, default=list)),
                ('habitaciones', models.CharField(max_length=100)),
                ('foto', models.URLField(max_length=500)),
                ('icono', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EspacioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('capacidad', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('tipos_evento', models.JSONField(blank=True, default=list)),
                ('foto', models.URLField(blank=True, max_length=500)),
                ('icono', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('caracteristicas', models.JSONField(blank=True, default=list)),
                ('foto', models.URLField(blank=True, max_length=500)),
                ('icono', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('oferta', models.JSONField(blank=True, default=list)),
                ('foto', models.URLField(max_length=500)),
                ('icono', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InformacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tagline', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('mision', models.TextField()),
                ('valores', models.JSONField(blank=True, default=list)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Informacion de la empresa',
                'verbose_name_plural': 'Informacion de la empresa',
            },
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('categoria', models.CharField(choices=[('Patrimonio', 'Patrimonio'), ('UNESCO', 'UNESCO'), ('Naturaleza', 'Naturaleza'), ('Cultura', 'Cultura'), ('Costa', 'Costa')], max_length=20)),
                ('categoria_color', models.CharField(default='#1B4F8A', max_length=20)),
                ('foto', models.URLField(max_length=500)),
                ('foto_hero', models.URLField(max_length=500)),
                ('resumen', models.TextField()),
                ('descripcion', models.TextField()),
                ('horario', models.CharField(max_length=160)),
                ('entrada', models.CharField(max_length=160)),
                ('ubicacion', models.CharField(max_length=255)),
                ('distancia', models.CharField(max_length=120)),
                ('consejos', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OtroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('anio', models.CharField(max_length=10)),
                ('icono', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicioCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('foto', models.URLField(blank=True, max_length=500)),
                ('icono', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
