# Generated by Django 5.2.13 on 2026-04-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldaba_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostal', models.CharField(max_length=200)),
                ('foto', models.URLField(blank=True, max_length=500)),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Suite', 'Suite')], max_length=20)),
                ('huespedes', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reserva', models.CharField(default='—', max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurante', models.CharField(max_length=200)),
                ('foto', models.URLField(blank=True, max_length=500)),
                ('numero', models.PositiveIntegerField()),
                ('capacidad', models.PositiveIntegerField()),
                ('ocupada', models.BooleanField(default=False)),
                ('reserva', models.CharField(default='—', max_length=200)),
                ('pago', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estado', models.CharField(choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada')], default='Libre', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('alojamiento', 'Alojamiento'), ('gastronomia', 'Gastronomia'), ('excursion', 'Excursion'), ('evento', 'Evento')], max_length=20)),
                ('establecimiento', models.CharField(max_length=200)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('personas', models.PositiveIntegerField(default=1)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservaExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.URLField(blank=True, max_length=500)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('personas', models.PositiveIntegerField()),
                ('guia', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.AddField(
            model_name='excursion',
            name='duracion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
