# Generated by Django 5.2.13 on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldaba_api", "0003_fix_accented_seed_data"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gastronomia",
            new_name="Restaurante",
        ),
        migrations.RenameField(
            model_name="excursion",
            old_name="nombre",
            new_name="destino",
        ),
        migrations.RemoveField(
            model_name="excursion",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="excursion",
            name="caracteristicas",
        ),
        migrations.AddField(
            model_name="excursion",
            name="personas",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="excursion",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="habitacion",
            name="numero",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name="habitacion",
            name="disponible",
        ),
        migrations.RemoveField(
            model_name="habitacion",
            name="hostal",
        ),
        migrations.RemoveField(
            model_name="habitacion",
            name="huespedes",
        ),
        migrations.RemoveField(
            model_name="habitacion",
            name="reserva",
        ),
        migrations.AddField(
            model_name="habitacion",
            name="estado",
            field=models.CharField(
                choices=[("Libre", "Libre"), ("Ocupada", "Ocupada"), ("Reservada", "Reservada")],
                default="Libre",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mesa",
            name="numero",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name="mesa",
            name="ocupada",
        ),
        migrations.RemoveField(
            model_name="mesa",
            name="reserva",
        ),
        migrations.AddField(
            model_name="mesa",
            name="precio",
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name="alojamiento",
            name="amenidades",
        ),
        migrations.RemoveField(
            model_name="alojamiento",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="alojamiento",
            name="habitaciones",
        ),
        migrations.AddField(
            model_name="alojamiento",
            name="habitacion",
            field=models.ForeignKey(
                blank=True,
                db_column="habitacion_numero",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alojamientos",
                to="aldaba_api.habitacion",
                to_field="numero",
            ),
        ),
        migrations.RemoveField(
            model_name="restaurante",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="restaurante",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="restaurante",
            name="oferta",
        ),
        migrations.AddField(
            model_name="restaurante",
            name="mesa",
            field=models.ForeignKey(
                blank=True,
                db_column="mesa_numero",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurantes",
                to="aldaba_api.mesa",
                to_field="numero",
            ),
        ),
        migrations.DeleteModel(
            name="Reserva",
        ),
    ]
