# Generated by Django 5.2.13 on 2026-04-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldaba_api', '0004_restructure_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacionempresa',
            options={'ordering': ['id'], 'verbose_name': 'Informacion de la empresa', 'verbose_name_plural': 'Informacion de la empresa'},
        ),
    ]
