# Generated by Django 5.2.13 on 2026-04-28 14:00

import django.db.models.deletion
from django.db import migrations, models


def migrate_habitaciones_to_new_fk(apps, schema_editor):
    """Migrate Habitacion.hostal from Alojamiento.habitacion relationship"""
    Alojamiento = apps.get_model('aldaba_api', 'Alojamiento')
    Habitacion = apps.get_model('aldaba_api', 'Habitacion')
    
    # For each Alojamiento with a habitacion FK, set that habitacion's hostal to point back
    for alojamiento in Alojamiento.objects.filter(habitacion__isnull=False):
        if alojamiento.habitacion:
            alojamiento.habitacion.hostal = alojamiento
            alojamiento.habitacion.save()
    
    # If there are Habitaciones without an Alojamiento, try to find a default one
    # or leave them null (they should be fixed manually)
    habitaciones_sin_alojamiento = Habitacion.objects.filter(hostal__isnull=True)
    if habitaciones_sin_alojamiento.exists() and Alojamiento.objects.exists():
        default_alojamiento = Alojamiento.objects.first()
        for habitacion in habitaciones_sin_alojamiento:
            habitacion.hostal = default_alojamiento
            habitacion.save()


def migrate_mesas_to_new_fk(apps, schema_editor):
    """Migrate Mesa.restaurante from Restaurante.mesa relationship"""
    Restaurante = apps.get_model('aldaba_api', 'Restaurante')
    Mesa = apps.get_model('aldaba_api', 'Mesa')
    
    # For each Restaurante with a mesa FK, set that mesa's restaurante to point back
    for restaurante in Restaurante.objects.filter(mesa__isnull=False):
        if restaurante.mesa:
            restaurante.mesa.restaurante = restaurante
            restaurante.mesa.save()
    
    # If there are Mesas without a Restaurante, assign default or leave null
    mesas_sin_restaurante = Mesa.objects.filter(restaurante__isnull=True)
    if mesas_sin_restaurante.exists() and Restaurante.objects.exists():
        default_restaurante = Restaurante.objects.first()
        for mesa in mesas_sin_restaurante:
            mesa.restaurante = default_restaurante
            mesa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aldaba_api', '0005_alter_informacionempresa_options'),
    ]

    operations = [
        # Step 1: Add new FK fields (nullable)
        migrations.AddField(
            model_name='habitacion',
            name='hostal',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='habitaciones',
                to='aldaba_api.alojamiento'
            ),
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mesas',
                to='aldaba_api.restaurante'
            ),
        ),
        
        # Step 2: Migrate data from old FK locations using Python
        migrations.RunPython(
            migrate_habitaciones_to_new_fk,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            migrate_mesas_to_new_fk,
            migrations.RunPython.noop,
        ),
        
        # Step 3: Remove old FK fields from parent tables
        migrations.RemoveField(
            model_name='alojamiento',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='mesa',
        ),
        
        # Step 5: Fix field lengths
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=3, unique=True),
        ),
        
        # Step 6: Update Mesa estados field
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(
                choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada')],
                default='Libre',
                max_length=20
            ),
        ),
    ]
