# Generated by Django 5.2.13 on 2026-04-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldaba_api', '0006_refactor_fk_relationships'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alojamiento',
            new_name='Hostal',
        ),
    ]
